apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xrijxi6mx-go-gitops
  description: This is GitOps manifest for xrijxi6mx-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xrijxi6mx-go
    backstage.io/kubernetes-id: xrijxi6mx-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xrijxi6mx-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xrijxi6mx-go
