apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xrijxi6mx-go
  janus-idp.io/tekton: xrijxi6mx-go
  backstage.io/kubernetes-id: xrijxi6mx-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xrijxi6mx-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
