apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xrijxi6mx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xrijxi6mx-go 
  name: xrijxi6mx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xrijxi6mx-go 
